namespace WorldServer.Game.Entity.Enums;

public enum OnlineStatus : byte
{
    None = 0,
    GameQA = 1,
    GameMaster = 2,
    GameMaster1 = 3,
    EventParticipant = 4,
    Disconnected = 5,
    WaitingforFriendListApproval = 6,
    WaitingforLinkshellApproval = 7,
    WaitingforFreeCompanyApproval = 8,
    NotFound = 9,
    Offline = 10,
    BattleMentor = 11,
    Busy = 12,
    PvP = 13,
    PlayingTripleTriad = 14,
    ViewingCutscene = 15,
    UsingaChocoboPorter = 16,
    AwayfromKeyboard = 17,
    CameraMode = 18,
    LookingforRepairs = 19,
    LookingtoRepair = 20,
    LookingtoMeldMateria = 21,
    Roleplaying = 22,
    LookingforParty = 23,
    SwordforHire = 24,
    WaitingforDutyFinder = 25,
    RecruitingPartyMembers = 26,
    Mentor = 27,
    PvEMentor = 28,
    TradeMentor = 29,
    PvPMentor = 30,
    Returner = 31,
    NewAdventurer = 32,
    AllianceLeader = 33,
    AlliancePartyLeader = 34,
    AlliancePartyMember = 35,
    PartyLeader = 36,
    PartyMember = 37,
    PartyLeaderCrossworld = 38,
    PartyMemberCrossworld = 39,
    AnotherWorld = 40,
    SharingDuty = 41,
    SimilarDuty = 42,
    InDuty = 43,
    TrialAdventurer = 44,
    FreeCompany = 45,
    GrandCompany = 46,
    Online = 47,
}